### PR TITLE
Use Promise.all for concurrent execution of promises fixes #11

### LINKED ISSUE #11: Use Promise.all for concurrent execution

### PR DESCRIPTION
**Pull request by itaditya**
Improve concurrency of bot by using concurrency

### CODE REVIEW

**Comment by Bartozzz** [comment]
Not sure why would it be better than the current implementation?

**Comment by itaditya** [comment]
In your current code, the `createComment()` function will be called only when the `addLabels()` function has resolved, but there is no need for  `createComment()` to wait right ? To avoid the waiting we can tell Javascript to run them concurrently

**Comment by itaditya** [comment]
Take a look at [this](https://youtu.be/9YkUCxvaLEk?t=468) @wesbos explains it much better

**Comment by Bartozzz** [comment]
Ah, I see – nice optimisation! It would be so great if you could also add a basic error handler which would log errors to the console, if there are any. A simple `try {} catch ()` should be enough. Thanks for contributing, by the way!

**Comment by itaditya** [comment]
I recommend to do that in a separate PR as the error handling is not related to this PR.

**Pull request merged**
